#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'findSubstring' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

def findSubstring(s, k):
  # Write your code here
  vowels = ['a','e','i','o','u']
  indexs = []
  for i in range(len(s)):
      if i+k <= len(s):
          j=0
          for lettre in s[i:i+k]:
              if lettre in vowels:
                  j+=1
          indexs.append(j)
  a = indexs.count(0)
  print(indexs)
  if a!= len(indexs):
    v = indexs.index(max(indexs))
    return s[v:v+k]   
  return ("Not Found")

    
if __name__ == '__main__':
    
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    k = int(input().strip())

    result = findSubstring(s, k)

    fptr.write(result + '\n')

    fptr.close()
